
create table company (
    id integer generated by default as identity,
    address varchar(255),
    city varchar(255),
    company_id varchar(255),
    country varchar(255),
    email varchar(255),
    name varchar(255),
    phone_number varchar(255),
    primary key (id)
);

alter table company add constraint UK_niu8sfil2gxywcru9ah3r4ec5 unique (name);

create table beneficial_owner (
    id integer generated by default as identity,
    name varchar(255),
    company_id integer not null,
    primary key (id)
);


alter table beneficial_owner add constraint FK_abecytsm12v5045bu9s18bdv8 foreign key (company_id) references company;


/*user schema*/

CREATE TABLE jhi_user (
  id bigint(20) NOT NULL AUTO_INCREMENT,
  login varchar(50) NOT NULL,
  password_hash varchar(60) DEFAULT NULL,
  first_name  varchar(50) DEFAULT NULL,
  last_name  varchar(50) DEFAULT NULL,
  email  varchar(100) DEFAULT NULL,
  activated  bit(1) NOT NULL,
  lang_key  varchar(5) DEFAULT NULL,
  activation_key  varchar(20) DEFAULT NULL,
  reset_key  varchar(20) DEFAULT NULL,
 // created_by  varchar(50) NOT NULL,
  //CREATED_DATE  timestamp NOT NULL,
  RESET_DATE  timestamp NULL DEFAULT NULL,
//  last_modified_by  varchar(50) DEFAULT NULL,
  //last_modified_date  timestamp NULL DEFAULT NULL,
  PRIMARY KEY ( id ),
  UNIQUE KEY login  ( login ),
  UNIQUE KEY idx_user_login  ( login ),
  UNIQUE KEY email  ( email ),
  UNIQUE KEY idx_user_email  ( email )
);


CREATE TABLE jhi_authority  (
  name  varchar(50) NOT NULL,
  PRIMARY KEY ( name )
);



CREATE TABLE jhi_user_authority  (
  user_id  bigint(20) NOT NULL,
  authority_name  varchar(50) NOT NULL,
  PRIMARY KEY ( user_id , authority_name ),
  //KEY fk_authority_name  ( authority_name ),
  CONSTRAINT fk_user_id  FOREIGN KEY ( user_id ) REFERENCES jhi_user  ( id ),
  CONSTRAINT fk_authority_name  FOREIGN KEY ( authority_name ) REFERENCES jhi_authority  ( name )
);

CREATE TABLE jhi_persistent_audit_event  (
  event_id  bigint(20) NOT NULL AUTO_INCREMENT,
  principal  varchar(255) NOT NULL,
  event_date  timestamp NULL DEFAULT NULL,
  event_type  varchar(255) DEFAULT NULL,
  PRIMARY KEY ( event_id )
  //KEY idx_persistent_audit_event  ( principal , event_date )
);

CREATE TABLE jhi_persistent_audit_evt_data  (
  event_id  bigint(20) NOT NULL,
  name  varchar(255) NOT NULL,
  value  varchar(255) DEFAULT NULL,
  PRIMARY KEY ( event_id , name ),
  //KEY idx_persistent_audit_evt_data  ( event_id ),
  CONSTRAINT fk_evt_pers_audit_evt_data  FOREIGN KEY ( event_id ) REFERENCES jhi_persistent_audit_event  ( event_id )
);


/*oAuth schema*/

CREATE TABLE oauth_access_token  (
  token_id  varchar(255) DEFAULT NULL,
  token  blob,
  authentication_id  varchar(255) NOT NULL,
  user_name  varchar(255) DEFAULT NULL,
  client_id  varchar(255) DEFAULT NULL,
  authentication  blob,
  refresh_token  varchar(255) DEFAULT NULL,
  PRIMARY KEY ( authentication_id ),
  //KEY fk_oauth_access_tokn_user_name  ( user_name ),
  CONSTRAINT fk_oauth_access_tokn_user_name  FOREIGN KEY ( user_name ) REFERENCES jhi_user  ( login )
);

CREATE TABLE oauth_approvals  (
  userId  varchar(255) DEFAULT NULL,
  clientId  varchar(255) DEFAULT NULL,
  scope  varchar(255) DEFAULT NULL,
  status  varchar(255) DEFAULT NULL,
  expiresAt  timestamp NULL DEFAULT NULL,
  lastModifiedAt  timestamp NULL DEFAULT NULL
);

CREATE TABLE oauth_client_details  (
  client_id  varchar(255) NOT NULL,
  resource_ids  varchar(255) DEFAULT NULL,
  client_secret  varchar(255) DEFAULT NULL,
  scope  varchar(255) DEFAULT NULL,
  authorized_grant_types  varchar(255) DEFAULT NULL,
  web_server_redirect_uri  varchar(255) DEFAULT NULL,
  authorities  varchar(255) DEFAULT NULL,
  access_token_validity  int(11) DEFAULT NULL,
  refresh_token_validity  int(11) DEFAULT NULL,
  additional_information  varchar(4096) DEFAULT NULL,
  autoapprove  varchar(4096) DEFAULT NULL,
  PRIMARY KEY (client_id)
);

CREATE TABLE oauth_client_token  (
  token_id  varchar(255) DEFAULT NULL,
  token  blob,
  authentication_id  varchar(255) DEFAULT NULL,
  user_name  varchar(255) DEFAULT NULL,
  client_id  varchar(255) DEFAULT NULL,
 // KEY fk_oauth_client_tokn_user_name  ( user_name ),
  CONSTRAINT fk_oauth_client_tokn_user_name  FOREIGN KEY ( user_name ) REFERENCES jhi_user  ( login )
);

CREATE TABLE oauth_code  (
  code  varchar(255) DEFAULT NULL
);


CREATE TABLE oauth_refresh_token  (
  token_id  varchar(255) DEFAULT NULL,
  token  blob,
  authentication  blob
);

INSERT INTO JHI_AUTHORITY VALUES ('ROLE_ADMIN');
INSERT INTO JHI_AUTHORITY VALUES ('ROLE_USER');